### ISSUE TITLE
Error on attempt upload

### ISSUE THREAD

**Issue by Roblox-Thot** [TheBlackArms/TheBlackArmsSDX#3]
Every time I click upload it errors out saying the avatar prefab cant be found.
I have not tried using a new project yet, but I should try a new one just let me know

**Comment by PhoenixAceVFX** [comment]
Can you send a screenshot of the error please? Preferably from the control output

**Comment by Roblox-Thot** [comment]
![image](https://user-images.githubusercontent.com/67937010/95033425-3b98f480-068c-11eb-9cb0-1ccaf7e6b200.png)
the full error about the missing file is : https://pastebin.com/raw/L5bynA5V

**Comment by PhoenixAceVFX** [comment]
Issue Caused by Rireal Script, Removal of said scripts should resolve issue.

**Comment by PhoenixAceVFX** [comment]
Issue moved to Discord and resolved on said platform.
