### ISSUE TITLE
Playmode

### ISSUE THREAD

**Issue by SenTakS** [TheBlackArms/TheBlackArmsSDX#4]
This sdk gives me compiler errors that idk how to fix

**Comment by Roblox-Thot** [comment]
You should probably add a screen shot of the error(s) because just saying you have them doesn't really help.

**Comment by PhoenixAceVFX** [comment]
yea that would help greatly if you sent screenshots of the console to show what is causing the error

**Comment by PhoenixAceVFX** [comment]
If there is not a response in the next few hours im closing this issue and marking it invalid due to lack of response

**Comment by PhoenixAceVFX** [comment]
Issue has been closed due to lack of response from initial user
