### ISSUE TITLE
cant Name avatar on upload

### ISSUE THREAD

**Issue by unlucky20** [TheBlackArms/TheBlackArmsSDX#5]
wont let me click in the name box to give the avatar a name to upload

**Comment by PhoenixAceVFX** [comment]
can you provide a screenshot of the issue?

**Comment by unlucky20** [comment]
![Capture](https://user-images.githubusercontent.com/77483232/113654303-2150cb00-965d-11eb-8a4f-bf0a4164d504.PNG)
when i get here i can not Click inside the name your avatar box to give it a name preventing me from uploading should have provided this from the get go sorry

**Comment by PhoenixAceVFX** [comment]
use a 16:9 resolution for the playmode view and try restarting unity, sometimes unity breaks your ability to interact with menus like this

**Comment by unlucky20** [comment]
dumb question where dose one change to  16:9

**Comment by PhoenixAceVFX** [comment]
you resize the window of the preview

**Comment by unlucky20** [comment]
![Capture](https://user-images.githubusercontent.com/77483232/113655248-1303ae80-965f-11eb-9501-85a3b7fe9c52.PNG) 

ok resized to 16:9 and restarted Twice just to be sure still cant Click to add a name

**Comment by PhoenixAceVFX** [comment]
hmm, i will look into it when im back in state for now keep the issue open and wait for me to respond again, its rather hard to help when out of state and on mobile

**Comment by unlucky20** [comment]
Rodger that  = ) yeah only lets me check the forget the limits box and move the music volume and of course hit upload thanks for the help

**Comment by PhoenixAceVFX** [comment]
ok now i am home and on my computer so i should be able to help alot more

**Comment by unlucky20** [comment]
alright well i fired up the project again and the problem is still there so what steps would you like me to take?

**Comment by PhoenixAceVFX** [comment]
hmm
can you show the console

**Comment by unlucky20** [comment]
sure would you like to move this to discord? 
![Capture](https://user-images.githubusercontent.com/77483232/113791660-c32df180-9709-11eb-9123-f6869e643e51.PNG)
![Capture1](https://user-images.githubusercontent.com/77483232/113791667-c628e200-9709-11eb-81dd-20a24ff27be4.PNG)

**Comment by PhoenixAceVFX** [comment]
can you filter it to only show ERRORS (the red triangle only)

**Comment by unlucky20** [comment]
console has no Red errors

**Comment by unlucky20** [comment]
![Capture](https://user-images.githubusercontent.com/77483232/113792284-2c623480-970b-11eb-8207-987954b180a4.PNG)

**Comment by PhoenixAceVFX** [comment]
then i cant really understand whats going on

**Comment by PhoenixAceVFX** [comment]
has any other sdk ever given this issue?

**Comment by unlucky20** [comment]
no other sdk has given me this problem soo yeah i dont know

**Comment by PhoenixAceVFX** [comment]
did you have any other sdk's imported before importing The Black Arms SDX?

**Comment by unlucky20** [comment]
yeah i restarted the project just to be on the safe side and still get all the way to the upload screen and can not click on anything but the forget the limits box upload and the volume slider with no errors in the console soo i have no idea what's going on

**Comment by PhoenixAceVFX** [comment]
fully remove The Black Arms SDX via file explorer WITH UNITY CLOSED and then reimport it, a clean reimport should fix everything
